language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}
  - composer update --prefer-source

script: phpunit --coverage-text
